pure_tumor_sample:
  sra_accession: "SRR7890879"
  sample_name: "HCC1395"
  platform: "ILLUMINA"

pure_normal_sample:
  sra_accession: "SRR7890880"
  sample_name: "HCC1395BL"
  platform: "ILLUMINA"

# this needs to be obtained from the provider of the capture kit, in this case,
# log in and search for download at: https://earray.chem.agilent.com/suredesign
capture_bed: "resources/S07604624_Covered.bed"

ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 110
  # Genome build
  build: GRCh38
  # Optionally, you can extract only the reads that map to a single chromosome,
  # please specify the chromosome in Ensembl notation (without any `chr` prefix).
  # This is usually only relevant for testing.
  # chromosome: 22

target_coverages:
  - 10
  - 20
  - 30
  - 40

target_normal_contaminations_percent:
  - 10
  - 30
  - 50
  - 70
  - 90

cutadapt:
  adapters: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  extra: ""