$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake workflow configuration file

type: object

properties:
  pure_tumor_sample:
    type: object
    properties:
      sra_accession:
        type: string
      sample_name:
        type: string
      platform:
        type: string
  required:
    - sra_accession
    - sample_name
    - platform
  pure_normal_sample:
    type: object
    properties:
      sra_accession:
        type: string
      sample_name:
        type: string
      platform:
        type: string
  required:
    - sra_accession
    - sample_name
    - platform
  capture_bed:
    type: string
  chromosome_to_extract:
    type: string
  target_coverages:
    type: array
    items:
      type: number
  target_normal_contaminations_percent:
    type: array
    items:
      type: number
  cutadapt:
    type: object
    properties:
      adapters:
        type: string
      extra:
        type: string
    required:
      - adapters
      - extra
required:
  - cutadapt
  - pure_tumor_sample
  - pure_normal_sample
  - capture_bed
  - target_coverages
  - target_normal_contaminations_percent
